//auth
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';


//client actions
export const GET_CLIENT = "GET_CLIENT";
export const FETCHING_DATA = "FETCHING_DATA";
export const RECEIVE_CLIENTS = "RECEIVE_CLIENTS";
export const TOOGLE_MODAL = "TOOGLE_MODAL";
export const ONCHANGE_FORM = "ONCHANGE_FORM";
export const SAVING_STATE = "SAVING_STATE";
export const SAVED_CLIENT_DATA = "SAVED_CLIENT_DATA";
export const GET_CLIENT_DETAIL_SUCCESS = "GET_CLIENT_DETAIL_SUCCESS";
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const PREP_CLIENT_TABLE_FOR_DATA = 'PREP_CLIENT_TABLE_FOR_DATA';
export const UPDATE_CLIENT_DATA = 'UPDATE_CLIENT_DATA';
export const DELETED_CLIENT_DATA = 'DELETED_CLIENT_DATA'

//project actions
export const FETCHING_PROJECT = "FETCHING_PROJECT";
export const SAVED_PROJECT_DATA = "SAVED_PROJECT_DATA";
export const TOGGLE_PROJECT_MODAL = 'TOGGLE_PROJECT_MODAL';
export const ONCHANGE_FORM_DATA = "ONCHANGE_FORM_DATA";
export const SET_PROJECT_LIST = 'SET_PROJECT_LIST'
export const GET_PROJECT_DETAIL_SUCCESS = "GET_PROJECT_DETAIL_SUCCESS";
export const UPDATE_PROJECT_DATA = "UPDATE_PROJECT_DATA";
export const EDIT_PROJECT ="EDIT_PROJECT";

//properties actions
export const TOGGLE_PROPERTIES_FORM = "TOGGLE_PROPERTIES_FORM";
export const SAVED_PROPERTIES_DATA = "SAVED_PROPERTIES_DATA";
export const ONCHANGE_FORM_PROPERTY = "ONCHANGE_FORM_PROPERTY";
export const ADD_ROOMS = "ADD_ROOMS";
export const REMOVE_ROOMS = "REMOVE_ROOMS";
export const GET_PROPERTIES = "GET_PROPERTIES"

//proposal actions
export const TOOGLE_PROPOSAL_MODAL = " TOOGLE_PROPOSAL_MODAL";
export const FETCHING_PROPOSAL = "FETCHING_PROPOSAL";
export const ONCHANGE_PROPOSAL_FORM = "ONCHANGE_PROPOSAL_FORM";
export const SAVING_STATE_PROPOSAL = "SAVING_STATE_PROPOSAL";
export const SAVED_PROPOSAL_DATA = "SAVED_PROPOSAL_DATA";
export const RECEIVE_PROPOSALS = "RECEIVE_PROPOSALS";
export const PREP_PROPOSAL_TABLE_FOR_DATA = "PREP_PROPOSAL_TABLE_FOR_DATA"
export const UPDATE_PROPOSAL_DATA = "UPDATE_PROPOSAL_DATA";

//photo actions
export const TOOGLE_PHOTO_MODAL = " TOOGLE_PHOTO_MODAL";
export const FETCHING_PHOTO = "FETCHING_PHOTO";
export const ONCHANGE_PHOTO_FORM = "ONCHANGE_PHOTO_FORM";
export const SAVING_STATE_PHOTO = "SAVING_STATE_PHOTO";
export const SAVED_PHOTO_DATA = "SAVED_PHOTO_DATA";
export const RECEIVE_PHOTO = "RECEIVE_PHOTO";
export const SET_PHOTO_LIST="SET_PHOTO_LIST";
export const EDIT_PHOTO='EDIT_PHOTO';
export const DELETED_PHOTO_DATA= "DELETED_PHOTO_DATA"
export const UPDATE_PHOTO_DATA = "UPDATE_PHOTO_DATA";

//users actions
export const GET_USER = "GET_USER";
export const FETCHING_DATA_USER = "FETCHING_DATA_USER";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const EDIT_USER_AGENCIES='EDIT_USER_AGENCIES';
export const TOGGLE_USER_MODAL = "TOGGLE_USER_MODAL";
export const SAVING_STATE_USER = "SAVING_STATE_USER";
export const ONCHANGE_FORM_USER = "ONCHANGE_FORM_USER";
export const SAVED_USER_DATA = "SAVED_USER_DATA";
//Agencies action
export const GET_AGENCIES = "GET_AGENCIES";
export const FETCHING_DATA_AGENCIES = "FETCHING_DATA_AGENCIES";
export const TOGGLE_AGENCIES_MODAL = "TOGGLE_AGENCIES_MODAL";
export const SAVING_STATE_AGENCIES = "SAVING_STATE_AGENCIES";
export const SAVED_AGENCIES_DATA = "SAVED_AGENCIES_DATA";
export const ONCHANGE_FORM_AGENCIES = "ONCHANGE_FORM_AGENCIES";
export const GET_AGENCIES_DETAIL_SUCCESS = "GET_AGENCIES_DETAIL_SUCCESS"
export const EDIT_AGENCIES='EDIT_AGENCIES';
export const UPDATE_AGENCIES_DATA = "UPDATE_AGENCIES_DATA";
